### ISSUE TITLE
support for django-4 and python 3.11

### ISSUE THREAD

**Issue by gecBurton** [nimasmi/django-gov-notify#9]
Hi, please could we extend the supported python versions to 3.11 and django to v4 [i-dot-ai:chore/upgrade-python-and-django](https://github.com/nimasmi/django-gov-notify/pull/8)

**Comment by zerolab** [comment]
Official support was added in #10, and #11 added 3.12 to the test matrix

**Comment by nimasmi** [comment]
Indeed. Thanks for your contribution in #8, @gecBurton. We should have closed this at the time.

**Comment by zerolab** [comment]
Ah, good catch @nimasmi. I missed #8 🤦🏼
